// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// Code generated by tools/operation-generator.go DO NOT EDIT.
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

package world

type BuildingInitOperation struct {
	NewConnections        []*Road
	AdditionalConnections []*Road
}

func (b *Building) InitOperation(o *BuildingInitOperation) {
	if o.NewConnections != nil {
		b.connections = o.NewConnections
	}

	if o.AdditionalConnections != nil {
		if b.connections == nil {
			b.connections = make([]*Road, 0)
		}

		b.connections = append(b.connections, o.AdditionalConnections...)
	}
}
