package world

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// Code generated by tools/operation-generator.go DO NOT EDIT
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

type BuildingInitOperation struct {
	NewConnections        []*Connection
	AdditionalConnections []*Connection
	ToRemoveConnections   []*Connection
}

func (b *Building) InitOperation(o *BuildingInitOperation) {
	if o.NewConnections != nil {
		b.connections = o.NewConnections
	}
	if o.AdditionalConnections != nil {
		if b.connections == nil {
			b.connections = make([]*Connection, 0)
		}
		b.connections = append(b.connections, o.AdditionalConnections...)
	}
	if o.ToRemoveConnections != nil {
		if b.connections != nil {
			for _, toRemove := range o.ToRemoveConnections {
				indexOf := -1
				for i, elm := range b.connections {
					if elm == toRemove {
						indexOf = i
						break
					}
				}
				if indexOf != -1 {
					lastIndex := len(b.connections) - 1
					b.connections[indexOf] = b.connections[lastIndex]
					b.connections = b.connections[:lastIndex]
				}
			}
		}
	}
}
