package world

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// Code generated by tools/operation-generator.go DO NOT EDIT
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

type RoadInitOperation struct {
	NewConnections        []*Road
	AdditionalConnections []*Road
}

func (r *Road) InitOperation(o *RoadInitOperation) {
	if o.NewConnections != nil {
		r.connections = o.NewConnections
	}
	if o.AdditionalConnections != nil {
		if r.connections == nil {
			r.connections = make([]*Road, 0)
		}
		r.connections = append(r.connections, o.AdditionalConnections...)
	}
}
