name: auto-release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        name: Release
        uses: ridedott/release-me-action@master