on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "::set-output name=version::(awk '$1=="go"{print $2}' go.mod)"
        id: go_mod

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ steps.go_mod.outputs.version }}
      - run: go fmt